### ISSUE TITLE
The extension makes Visual Studio unstable

### ISSUE THREAD

**Issue by ChrisBertrandIndus** [koszeggy/KGySoft.Drawing.Tools#5] opened 2021-10-08 09:01 UTC
1. When I visualize a Bitmap then close a Windows Forms app several times, the Visual Studio UI enters in troubles.

For example it can be blank after the application is closed:
![blank VS](https://user-images.githubusercontent.com/91182027/136527402-2201d7ee-715a-475d-afa9-890c2b67f384.png)

2. After the previous problem, if I try to run again the application (F5), VS loops indefinitely:
![VS looping](https://user-images.githubusercontent.com/91182027/136528239-2594e60e-88c8-4b2c-89cd-4bafc3b4bcdb.png)

Apparently, VS cannot read Program.cs again.
I can't even cancel that. I have to kill VS process.

No more problems after having uninstalled the extension.

VS : Version 16.11.4

Application : Windows Forms on .NET 5
dotnet --version : 5.0.401

Windows Update : up-to-date

**Comment by koszeggy** [comment] 2021-10-08 09:37
Unfortunately debugging a .NET Core (including .NET 5 and newer) application may lead to several issues.

Visual Studio is running on .NET Framework, and is able to use debugger visualizers written also in .NET Framework. The interop between the .NET [Core] application and the visualizer is far from perfect. I also have reported several issues to the Visual Studio Developer Community, some of them have already been fixed but some of them are [still pending](https://developercommunity.visualstudio.com/t/vs2022-throws-nullreferenceexception-if-a-debugger/1544699).

I'm afraid I cannot provide a 100% satisfying answer here but I can share some experiences:
* You may try VS2022. It's still in preview but I didn't really experience these indefinite hangups with that. It is not perfect either, the complete debugger and the Watch window often "loses control" (especially for the first time), but then a "Step over" (F10) in the debugger usually fixes things.
* For a more stable debugging experience I suggest adding also a .NET Framework target, eg. `net48` (of course, only if you don't use exclusive .NET Core features). It may be useful purely for debugging even if you release your product only for .NET 5.

**Comment by ChrisBertrandIndus** [comment] 2021-10-08 10:11
Thank you for your detailed info (and for your extension, by the way).

I will try VS 2022, and wait for MS to fix their bug.
Unfortunately, I can't use the workaround of multiple targets.

I let a message on [developercommunity.visualstudio.com](https://developercommunity.visualstudio.com/t/vs2022-throws-nullreferenceexception-if-a-debugger/1544699), and I encourage readers to do the same, or at least vote.

Thanks again for your efforts.

**Comment by koszeggy** [comment] 2021-11-15 13:36
Hopefully fixed by [this commit](https://github.com/koszeggy/KGySoft.Drawing.Tools/commit/ad7be2322f1391393df972ebfc22bd16a0fc4b8e).

VS does not really like large in-memory serializations but unfortunately it wasn't too verbose about describing the issue (and debugging the debugger itself is also really hard due to the remote app domains VS creates for visualizers). But I managed to reproduce something similar also with a Framework project that revealed that VS tends to dispose the debugged images even in the middle of the serialization to free up memory, which then causes access violation as the bitmap data is no longer valid... Now my non-Framework tests also seem much more stable.

**Comment by ChrisBertrandIndus** [comment] 2021-11-15 13:47
Thank you. I imagine debugging VS for an extension can be difficult. Especially without the source code of VS.
And now VS seems to be thread-intensive, I'm not that surprised it disposes objects at any moments.
Extensions have to be very robust nowadays !  ;-)

**Comment by koszeggy** [comment] 2021-11-17 12:48
Fixed by [v2.6.0](https://github.com/koszeggy/KGySoft.Drawing.Tools/releases/tag/v2.6.0)

**Closed as completed by koszeggy** 2021-11-17 12:48 UTC
