### ISSUE TITLE
Graphics causes an exception on .NET 5

### ISSUE THREAD

**Issue by ChrisBertrandIndus** [koszeggy/KGySoft.Drawing.Tools#6] opened 2021-10-08 09:11 UTC
When I try to visualize a Graphics, an exception occurs:

![exception visualizing Graphics](https://user-images.githubusercontent.com/91182027/136529522-32d23f11-2d3a-4503-b497-65c513205e30.png)

No problem when visualizing the Bitmap.

My code :

			using (Bitmap b = new(@"c:\temp\Image 01_C - 24 bits.png"))
			{
				using (Graphics g = Graphics.FromImage(b))
				{
					g.DrawEllipse(Pens.Green, 10, 20, 100, 200);
					g.DrawString("hello", SystemFonts.DefaultFont, Brushes.Red, default(PointF));
				}
			}

The breakpoint is juste after g.Drawing so Graphics is not disposed.

VS : Version 16.11.4

Application : Windows Forms on .NET 5, 32 and 64 bits, Debug.
dotnet --version : 5.0.401

Windows Update : up-to-date

No problem with a Windows Forms application on .NET Framework 4.8, 32 and 64 bits, Debug.

The stack:

         at KGySoft.Throw.InvalidOperationException(String message)
         at KGySoft.Reflection.Accessors.GetPropertyValue(Object instance, String propertyName)
         at KGySoft.Reflection.Accessors.IsSzArray(Type type)
         at KGySoft.CoreLibraries.TypeExtensions.IsZeroBasedArray(Type type)
         at KGySoft.Serialization.Binary.BinarySerializationFormatter.SerializationManager.WriteTypeNamesAndRanks(BinaryWriter bw, Type type, DataTypesEnumerator enumerator, Boolean allowOpenTypes)
         at KGySoft.Serialization.Binary.BinarySerializationFormatter.SerializationManager.WriteRootCollection(BinaryWriter bw, Object data, DataTypes dataType)
         at KGySoft.Serialization.Binary.BinarySerializationFormatter.SerializationManager.WriteRoot(BinaryWriter bw, Object obj)
         at KGySoft.Serialization.Binary.BinarySerializationFormatter.SerializeByWriter(BinaryWriter writer, Object data)
           at KGySoft.Serialization.Binary.BinarySerializer.SerializeByWriter(BinaryWriter writer, Object data, BinarySerializationOptions options)
           at KGySoft.Drawing.DebuggerVisualizers.Serialization.GraphicsSerializationInfo.Write(BinaryWriter bw)
           at KGySoft.Drawing.DebuggerVisualizers.Serialization.SerializationHelper.SerializeGraphicsInfo(Graphics g, Stream outgoingData)
         at KGySoft.Drawing.DebuggerVisualizers.Serialization.GraphicsSerializer.GetData(Object target, Stream outgoingData)
         at Microsoft.VisualStudio.DebuggerVisualizers.DebuggeeSide.Impl.ClrCustomVisualizerDebuggeeHost.GetData(Object visualizedObject)

The image:
![Image 01_C - 24 bits](https://user-images.githubusercontent.com/91182027/136530308-552f5404-ad58-4a9e-bd79-15188616fa92.png)

**Comment by koszeggy** [comment] 2021-10-08 09:18
Thank you for the report.

**Comment by koszeggy** [comment] 2021-10-08 12:13
I [fixed](https://github.com/koszeggy/KGySoft.CoreLibraries/commit/ae873b4bc63a2197f1e61dec7758beec4d401227) the root cause in the dependent library.

As it's targeting also .NET 6 and contains also a sort of .NET 6-relevant [changes](https://github.com/koszeggy/KGySoft.CoreLibraries/blob/Development/KGySoft.CoreLibraries/changelog.txt) an actual release can be expected after the release date of .NET 6.0.

**Comment by ChrisBertrandIndus** [comment] 2021-10-08 14:51
Thank you.

**Comment by koszeggy** [comment] 2021-11-17 12:48
Fixed by [v2.6.0](https://github.com/koszeggy/KGySoft.Drawing.Tools/releases/tag/v2.6.0)

**Closed as completed by koszeggy** 2021-11-17 12:48 UTC
Labels: bug
